version: '3.8'

services:

  movie_backend:
    build:
      context: ./movie_backend
      dockerfile: dockerfile
    ports:
      - "8011:8011"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Movies
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: Movies
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
